### PR TITLE
Newest guzzle version

### PR DESCRIPTION
**Pull request by MarioBlazek**
Uses new guzzle version from guzzlehttp. Also requires minimum PHP version to be 5.5 as guzzle v6 requires it.

### CODE REVIEW

**Comment by MarioBlazek** [comment]
ping @umpirsky :)

**Comment by umpirsky** [comment]
Looks good, we'll need to release new version with this. /cc @docteurklein

**Comment by MarioBlazek** [comment]
ping @umpirsky /cc @docteurklein :)

**Comment by m1guelpf** [comment]
Updates?

**Comment by MarioBlazek** [comment]
The Vim guy @docteurklein :) please review

**Comment by m1guelpf** [comment]
@umpirsky Merge?

**Comment by umpirsky** [comment]
@docteurklein Can merge. :)

**Comment by docteurklein** [comment]
sorry I'm way overbooked right now :)

**Comment by m1guelpf** [comment]
@docteurklein Could you tag a release?

**Pull request merged**
