### PR TITLE
Add dependents property

### PR DESCRIPTION
**Pull request by chadicus**
This pull request adds the dependents package property. 

packagist offers the number of packages that depend on the package. You can see the value here https://packagist.org/packages/chadicus/slim-oauth2-middleware.json

### CODE REVIEW

**Comment by chadicus** [comment]
What are the chances of this PR getting merged?

**Comment by chadicus** [comment]
Are there any issues with this pull request?

**Comment by chadicus** [comment]
@umpirsky are there any issues with this PR?

**Comment by chadicus** [comment]
@umpirsky @docteurklein is there an issue with this pull request preventing it from being merged?

**Comment by chadicus** [comment]
The build is failing on hhvm due to an error when travis attempts to install hhvm. It could be a result of the May 4th [Ubuntu Precise 12.04](https://blog.travis-ci.com/2017-05-04-precise-image-updates)

**Comment by chadicus** [comment]
Any chance of getting this PR merged before the next release?

**Comment by chadicus** [comment]
@NiR- Is there an issue with this pull request?  I'm happy to make any changes as needed.

**Comment by NiR-** [comment]
@chadicus You have some conflicts to resolve before I can merge it ;)

**Comment by chadicus** [comment]
@NiR- Conflicts resolved.

**Comment by NiR-** [comment]
Great! I'll create a new release :)

**Pull request merged**
