### PR TITLE
fix nullable declaration for php 8.4

### PR DESCRIPTION
**Pull request by tacman**

### CODE REVIEW

**Comment by robbieaverill** [comment]
Hi @tacman, I mentioned in #105 that I'd prefer to wait for phpstan to support PHP 8.4. Your latest commit highlights its incompatibility.

If you were to revert that commit, we can merge the nullable type change. This would allow you or others to install this package on PHP 8.4 using a `dev-master` constraint, with [`--ignore-platform-reqs=php+`](https://getcomposer.org/doc/03-cli.md#install-i) (assuming everything else works in 8.4).

What do you think?

**Comment by tacman** [comment]
great idea.  I forgot about that option to ignore the php version.

**Review by robbieaverill — APPROVED** [review]

**Comment by robbieaverill** [comment]
This fix is included in version v2.1.1

**Comment by tacman** [comment]
yep, working fine using the ignore option, thanks!

**Pull request merged**
